//go:build refc

// Generated by gen_wrappers.sh. Compiles celt/quant_bands.c as its own translation
// unit for the FIXED_POINT + DISABLE_FLOAT_API libopus oracle.
#include "libopus/celt/quant_bands.c"
