//go:build refc

// Generated by gen_wrappers.sh. Compiles silk/fixed/find_LPC_FIX.c as its own translation
// unit for the FIXED_POINT + DISABLE_FLOAT_API libopus oracle.
#include "libopus/silk/fixed/find_LPC_FIX.c"
