//go:build refc

// Generated by gen_wrappers.sh. Compiles silk/LPC_inv_pred_gain.c as its own translation
// unit for the FIXED_POINT + DISABLE_FLOAT_API libopus oracle.
#include "libopus/silk/LPC_inv_pred_gain.c"
