//go:build refc

// Generated by gen_wrappers.sh. Compiles silk/ana_filt_bank_1.c as its own translation
// unit for the FIXED_POINT + DISABLE_FLOAT_API libopus oracle.
#include "libopus/silk/ana_filt_bank_1.c"
