//go:build refc

// Generated by gen_wrappers.sh. Compiles silk/inner_prod_aligned.c as its own translation
// unit for the FIXED_POINT + DISABLE_FLOAT_API libopus oracle.
#include "libopus/silk/inner_prod_aligned.c"
