//go:build refc

// Generated by gen_wrappers.sh. Compiles silk/stereo_quant_pred.c as its own translation
// unit for the FIXED_POINT + DISABLE_FLOAT_API libopus oracle.
#include "libopus/silk/stereo_quant_pred.c"
