//go:build refc

// Generated by gen_wrappers.sh. Compiles silk/tables_pitch_lag.c as its own translation
// unit for the FIXED_POINT + DISABLE_FLOAT_API libopus oracle.
#include "libopus/silk/tables_pitch_lag.c"
