/***********************************************************************
Copyright (c) 2006-2011, Skype Limited. All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
- Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
- Neither the name of Internet Society, IETF or IETF Trust, nor the
names of specific contributors, may be used to endorse or promote
products derived from this software without specific prior written
permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
***********************************************************************/

package silk

// SILK resampler ROM coefficient tables, transliterated directly from
// silk/resampler_rom.c and silk/resampler_rom.h (libopus v1.6.1) for the frozen
// FIXED_POINT, DISABLE_FLOAT_API decoder build. These tables are small and static,
// so they are hand-transcribed here rather than machine-generated by cmd/gentables;
// the differential test in internal/reftest (which runs the real C resampler over
// the real ROM) validates every value bit-exact, so a transcription error cannot go
// unnoticed. The 96 kHz QEXT-only rates are out of scope (ENABLE_QEXT undefined).
//
// The negated up2/notch coefficients (e.g. 39083 - 65536) are written out to their
// int16 value exactly as the C compiler evaluates them.
//
// Type mapping (silk/typedef.h): opus_int16 -> int16.

// FIR filter orders for the fractional down-samplers and the FIR interpolation of
// the 2x-upsampling fractional resampler (silk/resampler_rom.h).
const (
	resamplerDownOrderFIR0 = 18 // RESAMPLER_DOWN_ORDER_FIR0
	resamplerDownOrderFIR1 = 24 // RESAMPLER_DOWN_ORDER_FIR1
	resamplerDownOrderFIR2 = 36 // RESAMPLER_DOWN_ORDER_FIR2
	resamplerOrderFIR12    = 8  // RESAMPLER_ORDER_FIR_12
)

// Tables for 2x upsampler, high quality (silk/resampler_rom.h). Second-order
// allpass coefficients, Q15. 39083 - 65536 = -26453; 55542 - 65536 = -9994.
var (
	silkResamplerUp2HQ0 = [3]int16{1746, 14986, -26453} // silk_resampler_up2_hq_0
	silkResamplerUp2HQ1 = [3]int16{6854, 25769, -9994}  // silk_resampler_up2_hq_1
)

// Tables with IIR and FIR coefficients for the fractional down-samplers
// (silk/resampler_rom.c). The first two entries of each table are the AR2 filter
// coefficients (A_Q14); the remainder are the polyphase FIR coefficients. On the
// decoder path (Fs_in in {8,12,16} kHz) silk_resampler_init reaches only the 3:4,
// 2:3 and 1:2 down-samplers (16->12, 12->8, 16->8); the 1:3, 1:4 and 1:6 tables are
// referenced by the encoder-rate branches of ResamplerInit and are kept so the init
// transliteration stays complete and diffable.
var (
	// silk_Resampler_3_4_COEFS[ 2 + 3 * RESAMPLER_DOWN_ORDER_FIR0 / 2 ]
	silkResampler34COEFS = []int16{
		-20694, -13867,
		-49, 64, 17, -157, 353, -496, 163, 11047, 22205,
		-39, 6, 91, -170, 186, 23, -896, 6336, 19928,
		-19, -36, 102, -89, -24, 328, -951, 2568, 15909,
	}

	// silk_Resampler_2_3_COEFS[ 2 + 2 * RESAMPLER_DOWN_ORDER_FIR0 / 2 ]
	silkResampler23COEFS = []int16{
		-14457, -14019,
		64, 128, -122, 36, 310, -768, 584, 9267, 17733,
		12, 128, 18, -142, 288, -117, -865, 4123, 14459,
	}

	// silk_Resampler_1_2_COEFS[ 2 + RESAMPLER_DOWN_ORDER_FIR1 / 2 ]
	silkResampler12COEFS = []int16{
		616, -14323,
		-10, 39, 58, -46, -84, 120, 184, -315, -541, 1284, 5380, 9024,
	}

	// silk_Resampler_1_3_COEFS[ 2 + RESAMPLER_DOWN_ORDER_FIR2 / 2 ]
	silkResampler13COEFS = []int16{
		16102, -15162,
		-13, 0, 20, 26, 5, -31, -43, -4, 65, 90, 7, -157, -248, -44, 593, 1583, 2612, 3271,
	}

	// silk_Resampler_1_4_COEFS[ 2 + RESAMPLER_DOWN_ORDER_FIR2 / 2 ]
	silkResampler14COEFS = []int16{
		22500, -15099,
		3, -14, -20, -15, 2, 25, 37, 25, -16, -71, -107, -79, 50, 292, 623, 982, 1288, 1464,
	}

	// silk_Resampler_1_6_COEFS[ 2 + RESAMPLER_DOWN_ORDER_FIR2 / 2 ]
	silkResampler16COEFS = []int16{
		27540, -15257,
		17, 12, 8, 1, -10, -22, -30, -32, -22, 3, 44, 100, 168, 243, 317, 381, 429, 455,
	}
)

// Table with interpolation fractions of 1/24, 3/24, 5/24, ..., 23/24
// (silk/resampler_rom.c: silk_resampler_frac_FIR_12[ 12 ][ RESAMPLER_ORDER_FIR_12 / 2 ]).
var silkResamplerFracFIR12 = [12][resamplerOrderFIR12 / 2]int16{
	{189, -600, 617, 30567},
	{117, -159, -1070, 29704},
	{52, 221, -2392, 28276},
	{-4, 529, -3350, 26341},
	{-48, 758, -3956, 23973},
	{-80, 905, -4235, 21254},
	{-99, 972, -4222, 18278},
	{-107, 967, -3957, 15143},
	{-103, 896, -3487, 11950},
	{-91, 773, -2865, 8798},
	{-71, 611, -2143, 5784},
	{-46, 425, -1375, 2996},
}
