package main

import (
	"fmt"
	"go/format"
	"strings"
)

// silkSchema is the expected length of every key the SILK dumper emits. The
// lengths mirror the upstream array declarations (silk/tables.h and the
// tables_*.c files); validateSchema re-asserts each so a submodule reshape
// fails at generation time.
var silkSchema = map[string]int{
	// tables_gain.c
	"gainICDF":      24, // silk_gain_iCDF[3][8]
	"deltaGainICDF": 41, // silk_delta_gain_iCDF

	// tables_LTP.c
	"ltpPerIndexICDF": 3,
	"ltpGainICDF0":    8,
	"ltpGainICDF1":    16,
	"ltpGainICDF2":    32,
	"ltpGainBITS0":    8,
	"ltpGainBITS1":    16,
	"ltpGainBITS2":    32,
	"ltpVQ0":          40,  // silk_LTP_gain_vq_0[8][5]
	"ltpVQ1":          80,  // silk_LTP_gain_vq_1[16][5]
	"ltpVQ2":          160, // silk_LTP_gain_vq_2[32][5]
	"ltpVQGain0":      8,
	"ltpVQGain1":      16,
	"ltpVQGain2":      32,
	"ltpVQSizes":      3,

	// tables_pitch_lag.c
	"pitchLagICDF":           32,
	"pitchDeltaICDF":         21,
	"pitchContourICDF":       34,
	"pitchContourNBICDF":     11,
	"pitchContour10msICDF":   12,
	"pitchContour10msNBICDF": 3,

	// pitch_est_tables.c (contour codebooks used by silk_decode_pitch)
	"cbLagsStage2":      44,  // silk_CB_lags_stage2[4][11]
	"cbLagsStage3":      136, // silk_CB_lags_stage3[4][34]
	"cbLagsStage2_10ms": 6,   // silk_CB_lags_stage2_10_ms[2][3]
	"cbLagsStage3_10ms": 24,  // silk_CB_lags_stage3_10_ms[2][12]

	// tables_pulses_per_block.c
	"maxPulsesTable":        4,
	"pulsesPerBlockICDF":    180, // [10][18]
	"pulsesPerBlockBITSQ5":  162, // [9][18]
	"rateLevelsICDF":        18,  // [2][9]
	"rateLevelsBITSQ5":      18,  // [2][9]
	"shellCodeTable0":       152,
	"shellCodeTable1":       152,
	"shellCodeTable2":       152,
	"shellCodeTable3":       152,
	"shellCodeTableOffsets": 17,
	"signICDF":              42,

	// tables_other.c
	"stereoPredQuantQ13":          16,
	"stereoPredJointICDF":         25,
	"stereoOnlyCodeMidICDF":       2,
	"lbrrFlags2ICDF":              3,
	"lbrrFlags3ICDF":              7,
	"lsbICDF":                     2,
	"ltpScaleICDF":                3,
	"typeOffsetVADICDF":           4,
	"typeOffsetNoVADICDF":         2,
	"nlsfInterpolationFactorICDF": 5,
	"quantizationOffsetsQ10":      4, // [2][2]
	"ltpScalesTableQ14":           3,
	"uniform3ICDF":                3,
	"uniform4ICDF":                4,
	"uniform5ICDF":                5,
	"uniform6ICDF":                6,
	"uniform8ICDF":                8,
	"nlsfEXTICDF":                 7,
	"transitionLPBQ28":            15, // [5][3]
	"transitionLPAQ28":            10, // [5][2]

	// table_LSF_cos.c
	"lsfCosTabFIXQ12": 129, // LSF_COS_TAB_SZ_FIX + 1

	// tables_NLSF_CB_NB_MB.c
	"nbmbScalars":     4,
	"nbmbCB1NLSFQ8":   320,
	"nbmbCB1WghtQ9":   320,
	"nbmbCB1ICDF":     64,
	"nbmbPredQ8":      18,
	"nbmbEcSel":       160,
	"nbmbEcICDF":      72,
	"nbmbEcRatesQ5":   72,
	"nbmbDeltaMinQ15": 11,

	// tables_NLSF_CB_WB.c
	"wbScalars":     4,
	"wbCB1NLSFQ8":   512,
	"wbCB1WghtQ9":   512,
	"wbCB1ICDF":     64,
	"wbPredQ8":      30,
	"wbEcSel":       256,
	"wbEcICDF":      72,
	"wbEcRatesQ5":   72,
	"wbDeltaMinQ15": 17,
}

// emitSILK assembles and gofmt's the generated SILK source from the parsed
// tables.
func emitSILK(t map[string][]int) ([]byte, error) {
	var b strings.Builder

	fmt.Fprintf(&b, "// Code generated by cmd/gentables; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Source: libopus silk/ static tables (tables_NLSF_CB_NB_MB.c,\n")
	fmt.Fprintf(&b, "// tables_NLSF_CB_WB.c, tables_gain.c, tables_LTP.c, tables_other.c,\n")
	fmt.Fprintf(&b, "// tables_pitch_lag.c, tables_pulses_per_block.c, table_LSF_cos.c,\n")
	fmt.Fprintf(&b, "// pitch_est_tables.c), upstream tag %s. Method: compile and run\n", upstreamTag)
	fmt.Fprintf(&b, "// cmd/gentables/cdump/dump_silk.c under -DFIXED_POINT -DDISABLE_FLOAT_API\n")
	fmt.Fprintf(&b, "// and transcribe its dump. The encoder-only pitch-analysis parameter tables\n")
	fmt.Fprintf(&b, "// (the stage-3 lag ranges and per-complexity codebook counts) are\n")
	fmt.Fprintf(&b, "// intentionally omitted. Regenerate with `go generate ./internal/silk/...`.\n\n")
	fmt.Fprintf(&b, "package silk\n\n")

	// --- Gain tables (tables_gain.c) ---
	emitArray2D(&b, "silkGainICDF", "silkGainICDF mirrors silk_gain_iCDF[3][N_LEVELS_QGAIN/8].", "byte", 3, 8, t["gainICDF"])
	emitSlice(&b, "silkDeltaGainICDF", "silkDeltaGainICDF mirrors silk_delta_gain_iCDF.", "byte", t["deltaGainICDF"], 12)

	// --- LTP tables (tables_LTP.c) ---
	emitSlice(&b, "silkLTPPerIndexICDF", "silkLTPPerIndexICDF mirrors silk_LTP_per_index_iCDF.", "byte", t["ltpPerIndexICDF"], 12)
	emitSlice(&b, "silkLTPGainICDF0", "silkLTPGainICDF0 mirrors silk_LTP_gain_iCDF_0.", "byte", t["ltpGainICDF0"], 12)
	emitSlice(&b, "silkLTPGainICDF1", "silkLTPGainICDF1 mirrors silk_LTP_gain_iCDF_1.", "byte", t["ltpGainICDF1"], 12)
	emitSlice(&b, "silkLTPGainICDF2", "silkLTPGainICDF2 mirrors silk_LTP_gain_iCDF_2.", "byte", t["ltpGainICDF2"], 12)
	emitPtrSlice(&b, "silkLTPGainICDFPtrs", "silkLTPGainICDFPtrs mirrors silk_LTP_gain_iCDF_ptrs[NB_LTP_CBKS].", "byte",
		[]string{"silkLTPGainICDF0", "silkLTPGainICDF1", "silkLTPGainICDF2"})
	emitSlice(&b, "silkLTPGainBITSQ50", "silkLTPGainBITSQ50 mirrors silk_LTP_gain_BITS_Q5_0.", "byte", t["ltpGainBITS0"], 12)
	emitSlice(&b, "silkLTPGainBITSQ51", "silkLTPGainBITSQ51 mirrors silk_LTP_gain_BITS_Q5_1.", "byte", t["ltpGainBITS1"], 12)
	emitSlice(&b, "silkLTPGainBITSQ52", "silkLTPGainBITSQ52 mirrors silk_LTP_gain_BITS_Q5_2.", "byte", t["ltpGainBITS2"], 12)
	emitPtrSlice(&b, "silkLTPGainBITSQ5Ptrs", "silkLTPGainBITSQ5Ptrs mirrors silk_LTP_gain_BITS_Q5_ptrs[NB_LTP_CBKS].", "byte",
		[]string{"silkLTPGainBITSQ50", "silkLTPGainBITSQ51", "silkLTPGainBITSQ52"})
	emitSlice(&b, "silkLTPGainVQ0", "silkLTPGainVQ0 mirrors silk_LTP_gain_vq_0[8][5], row-major (Q7).", "int8", t["ltpVQ0"], 5)
	emitSlice(&b, "silkLTPGainVQ1", "silkLTPGainVQ1 mirrors silk_LTP_gain_vq_1[16][5], row-major (Q7).", "int8", t["ltpVQ1"], 5)
	emitSlice(&b, "silkLTPGainVQ2", "silkLTPGainVQ2 mirrors silk_LTP_gain_vq_2[32][5], row-major (Q7).", "int8", t["ltpVQ2"], 5)
	emitPtrSlice(&b, "silkLTPVQPtrsQ7", "silkLTPVQPtrsQ7 mirrors silk_LTP_vq_ptrs_Q7[NB_LTP_CBKS]; each element is a\n// codebook flattened row-major with stride LTP_ORDER (5).", "int8",
		[]string{"silkLTPGainVQ0", "silkLTPGainVQ1", "silkLTPGainVQ2"})
	emitSlice(&b, "silkLTPGainVQ0Gain", "silkLTPGainVQ0Gain mirrors silk_LTP_gain_vq_0_gain.", "byte", t["ltpVQGain0"], 12)
	emitSlice(&b, "silkLTPGainVQ1Gain", "silkLTPGainVQ1Gain mirrors silk_LTP_gain_vq_1_gain.", "byte", t["ltpVQGain1"], 12)
	emitSlice(&b, "silkLTPGainVQ2Gain", "silkLTPGainVQ2Gain mirrors silk_LTP_gain_vq_2_gain.", "byte", t["ltpVQGain2"], 12)
	emitPtrSlice(&b, "silkLTPVQGainPtrsQ7", "silkLTPVQGainPtrsQ7 mirrors silk_LTP_vq_gain_ptrs_Q7[NB_LTP_CBKS].", "byte",
		[]string{"silkLTPGainVQ0Gain", "silkLTPGainVQ1Gain", "silkLTPGainVQ2Gain"})
	emitSlice(&b, "silkLTPVQSizes", "silkLTPVQSizes mirrors silk_LTP_vq_sizes[NB_LTP_CBKS].", "int8", t["ltpVQSizes"], 12)

	// --- Pitch lag / contour iCDFs (tables_pitch_lag.c) ---
	emitSlice(&b, "silkPitchLagICDF", "silkPitchLagICDF mirrors silk_pitch_lag_iCDF.", "byte", t["pitchLagICDF"], 12)
	emitSlice(&b, "silkPitchDeltaICDF", "silkPitchDeltaICDF mirrors silk_pitch_delta_iCDF.", "byte", t["pitchDeltaICDF"], 12)
	emitSlice(&b, "silkPitchContourICDF", "silkPitchContourICDF mirrors silk_pitch_contour_iCDF.", "byte", t["pitchContourICDF"], 12)
	emitSlice(&b, "silkPitchContourNBICDF", "silkPitchContourNBICDF mirrors silk_pitch_contour_NB_iCDF.", "byte", t["pitchContourNBICDF"], 12)
	emitSlice(&b, "silkPitchContour10msICDF", "silkPitchContour10msICDF mirrors silk_pitch_contour_10_ms_iCDF.", "byte", t["pitchContour10msICDF"], 12)
	emitSlice(&b, "silkPitchContour10msNBICDF", "silkPitchContour10msNBICDF mirrors silk_pitch_contour_10_ms_NB_iCDF.", "byte", t["pitchContour10msNBICDF"], 12)

	// --- Pitch contour codebooks consumed by silk_decode_pitch
	// (pitch_est_tables.c). ---
	emitArray2D(&b, "silkCBLagsStage2", "silkCBLagsStage2 mirrors silk_CB_lags_stage2[PE_MAX_NB_SUBFR][PE_NB_CBKS_STAGE2_EXT].", "int8", 4, 11, t["cbLagsStage2"])
	emitArray2D(&b, "silkCBLagsStage3", "silkCBLagsStage3 mirrors silk_CB_lags_stage3[PE_MAX_NB_SUBFR][PE_NB_CBKS_STAGE3_MAX].", "int8", 4, 34, t["cbLagsStage3"])
	emitArray2D(&b, "silkCBLagsStage210ms", "silkCBLagsStage210ms mirrors silk_CB_lags_stage2_10_ms[PE_MAX_NB_SUBFR>>1][PE_NB_CBKS_STAGE2_10MS].", "int8", 2, 3, t["cbLagsStage2_10ms"])
	emitArray2D(&b, "silkCBLagsStage310ms", "silkCBLagsStage310ms mirrors silk_CB_lags_stage3_10_ms[PE_MAX_NB_SUBFR>>1][PE_NB_CBKS_STAGE3_10MS].", "int8", 2, 12, t["cbLagsStage3_10ms"])

	// --- Pulses-per-block / shell coding (tables_pulses_per_block.c) ---
	emitSlice(&b, "silkMaxPulsesTable", "silkMaxPulsesTable mirrors silk_max_pulses_table.", "byte", t["maxPulsesTable"], 12)
	emitArray2D(&b, "silkPulsesPerBlockICDF", "silkPulsesPerBlockICDF mirrors silk_pulses_per_block_iCDF[N_RATE_LEVELS][SILK_MAX_PULSES+2].", "byte", 10, 18, t["pulsesPerBlockICDF"])
	emitArray2D(&b, "silkPulsesPerBlockBITSQ5", "silkPulsesPerBlockBITSQ5 mirrors silk_pulses_per_block_BITS_Q5[N_RATE_LEVELS-1][SILK_MAX_PULSES+2].", "byte", 9, 18, t["pulsesPerBlockBITSQ5"])
	emitArray2D(&b, "silkRateLevelsICDF", "silkRateLevelsICDF mirrors silk_rate_levels_iCDF[2][N_RATE_LEVELS-1].", "byte", 2, 9, t["rateLevelsICDF"])
	emitArray2D(&b, "silkRateLevelsBITSQ5", "silkRateLevelsBITSQ5 mirrors silk_rate_levels_BITS_Q5[2][N_RATE_LEVELS-1].", "byte", 2, 9, t["rateLevelsBITSQ5"])
	emitSlice(&b, "silkShellCodeTable0", "silkShellCodeTable0 mirrors silk_shell_code_table0.", "byte", t["shellCodeTable0"], 12)
	emitSlice(&b, "silkShellCodeTable1", "silkShellCodeTable1 mirrors silk_shell_code_table1.", "byte", t["shellCodeTable1"], 12)
	emitSlice(&b, "silkShellCodeTable2", "silkShellCodeTable2 mirrors silk_shell_code_table2.", "byte", t["shellCodeTable2"], 12)
	emitSlice(&b, "silkShellCodeTable3", "silkShellCodeTable3 mirrors silk_shell_code_table3.", "byte", t["shellCodeTable3"], 12)
	emitSlice(&b, "silkShellCodeTableOffsets", "silkShellCodeTableOffsets mirrors silk_shell_code_table_offsets.", "byte", t["shellCodeTableOffsets"], 12)
	emitSlice(&b, "silkSignICDF", "silkSignICDF mirrors silk_sign_iCDF.", "byte", t["signICDF"], 7)

	// --- Stereo, LBRR, misc entropy tables (tables_other.c) ---
	emitSlice(&b, "silkStereoPredQuantQ13", "silkStereoPredQuantQ13 mirrors silk_stereo_pred_quant_Q13[STEREO_QUANT_TAB_SIZE].", "int16", t["stereoPredQuantQ13"], 8)
	emitSlice(&b, "silkStereoPredJointICDF", "silkStereoPredJointICDF mirrors silk_stereo_pred_joint_iCDF.", "byte", t["stereoPredJointICDF"], 12)
	emitSlice(&b, "silkStereoOnlyCodeMidICDF", "silkStereoOnlyCodeMidICDF mirrors silk_stereo_only_code_mid_iCDF.", "byte", t["stereoOnlyCodeMidICDF"], 12)
	emitSlice(&b, "silkLBRRFlags2ICDF", "silkLBRRFlags2ICDF mirrors silk_LBRR_flags_2_iCDF.", "byte", t["lbrrFlags2ICDF"], 12)
	emitSlice(&b, "silkLBRRFlags3ICDF", "silkLBRRFlags3ICDF mirrors silk_LBRR_flags_3_iCDF.", "byte", t["lbrrFlags3ICDF"], 12)
	emitPtrSlice(&b, "silkLBRRFlagsICDFPtr", "silkLBRRFlagsICDFPtr mirrors silk_LBRR_flags_iCDF_ptr[2].", "byte",
		[]string{"silkLBRRFlags2ICDF", "silkLBRRFlags3ICDF"})
	emitSlice(&b, "silkLSBICDF", "silkLSBICDF mirrors silk_lsb_iCDF.", "byte", t["lsbICDF"], 12)
	emitSlice(&b, "silkLTPscaleICDF", "silkLTPscaleICDF mirrors silk_LTPscale_iCDF.", "byte", t["ltpScaleICDF"], 12)
	emitSlice(&b, "silkTypeOffsetVADICDF", "silkTypeOffsetVADICDF mirrors silk_type_offset_VAD_iCDF.", "byte", t["typeOffsetVADICDF"], 12)
	emitSlice(&b, "silkTypeOffsetNoVADICDF", "silkTypeOffsetNoVADICDF mirrors silk_type_offset_no_VAD_iCDF.", "byte", t["typeOffsetNoVADICDF"], 12)
	emitSlice(&b, "silkNLSFInterpolationFactorICDF", "silkNLSFInterpolationFactorICDF mirrors silk_NLSF_interpolation_factor_iCDF.", "byte", t["nlsfInterpolationFactorICDF"], 12)
	emitArray2D(&b, "silkQuantizationOffsetsQ10", "silkQuantizationOffsetsQ10 mirrors silk_Quantization_Offsets_Q10[2][2].", "int16", 2, 2, t["quantizationOffsetsQ10"])
	emitSlice(&b, "silkLTPScalesTableQ14", "silkLTPScalesTableQ14 mirrors silk_LTPScales_table_Q14.", "int16", t["ltpScalesTableQ14"], 8)
	emitSlice(&b, "silkUniform3ICDF", "silkUniform3ICDF mirrors silk_uniform3_iCDF.", "byte", t["uniform3ICDF"], 12)
	emitSlice(&b, "silkUniform4ICDF", "silkUniform4ICDF mirrors silk_uniform4_iCDF.", "byte", t["uniform4ICDF"], 12)
	emitSlice(&b, "silkUniform5ICDF", "silkUniform5ICDF mirrors silk_uniform5_iCDF.", "byte", t["uniform5ICDF"], 12)
	emitSlice(&b, "silkUniform6ICDF", "silkUniform6ICDF mirrors silk_uniform6_iCDF.", "byte", t["uniform6ICDF"], 12)
	emitSlice(&b, "silkUniform8ICDF", "silkUniform8ICDF mirrors silk_uniform8_iCDF.", "byte", t["uniform8ICDF"], 12)
	emitSlice(&b, "silkNLSFEXTICDF", "silkNLSFEXTICDF mirrors silk_NLSF_EXT_iCDF.", "byte", t["nlsfEXTICDF"], 12)
	emitArray2D(&b, "silkTransitionLPBQ28", "silkTransitionLPBQ28 mirrors silk_Transition_LP_B_Q28[TRANSITION_INT_NUM][TRANSITION_NB].", "int32", 5, 3, t["transitionLPBQ28"])
	emitArray2D(&b, "silkTransitionLPAQ28", "silkTransitionLPAQ28 mirrors silk_Transition_LP_A_Q28[TRANSITION_INT_NUM][TRANSITION_NA].", "int32", 5, 2, t["transitionLPAQ28"])

	// --- LSF cosine table (table_LSF_cos.c) ---
	emitSlice(&b, "silkLSFCosTabFIXQ12", "silkLSFCosTabFIXQ12 mirrors silk_LSFCosTab_FIX_Q12[LSF_COS_TAB_SZ_FIX+1].", "int16", t["lsfCosTabFIXQ12"], 8)

	// --- NLSF NB/MB codebook (tables_NLSF_CB_NB_MB.c) ---
	emitSlice(&b, "silkNLSFCB1NBMBQ8", "silkNLSFCB1NBMBQ8 mirrors silk_NLSF_CB1_NB_MB_Q8.", "byte", t["nbmbCB1NLSFQ8"], 10)
	emitSlice(&b, "silkNLSFCB1WghtQ9", "silkNLSFCB1WghtQ9 mirrors silk_NLSF_CB1_Wght_Q9.", "int16", t["nbmbCB1WghtQ9"], 10)
	emitSlice(&b, "silkNLSFCB1ICDFNBMB", "silkNLSFCB1ICDFNBMB mirrors silk_NLSF_CB1_iCDF_NB_MB.", "byte", t["nbmbCB1ICDF"], 12)
	emitSlice(&b, "silkNLSFPredNBMBQ8", "silkNLSFPredNBMBQ8 mirrors silk_NLSF_PRED_NB_MB_Q8.", "byte", t["nbmbPredQ8"], 12)
	emitSlice(&b, "silkNLSFCB2SelectNBMB", "silkNLSFCB2SelectNBMB mirrors silk_NLSF_CB2_SELECT_NB_MB.", "byte", t["nbmbEcSel"], 16)
	emitSlice(&b, "silkNLSFCB2ICDFNBMB", "silkNLSFCB2ICDFNBMB mirrors silk_NLSF_CB2_iCDF_NB_MB.", "byte", t["nbmbEcICDF"], 9)
	emitSlice(&b, "silkNLSFCB2BITSNBMBQ5", "silkNLSFCB2BITSNBMBQ5 mirrors silk_NLSF_CB2_BITS_NB_MB_Q5.", "byte", t["nbmbEcRatesQ5"], 9)
	emitSlice(&b, "silkNLSFDeltaMinNBMBQ15", "silkNLSFDeltaMinNBMBQ15 mirrors silk_NLSF_DELTA_MIN_NB_MB_Q15.", "int16", t["nbmbDeltaMinQ15"], 11)
	emitNLSFCB(&b, "silkNLSFCBNBMB", "silkNLSFCBNBMB mirrors silk_NLSF_CB_NB_MB (silk/tables_NLSF_CB_NB_MB.c).", t["nbmbScalars"],
		"silkNLSFCB1NBMBQ8", "silkNLSFCB1WghtQ9", "silkNLSFCB1ICDFNBMB", "silkNLSFPredNBMBQ8",
		"silkNLSFCB2SelectNBMB", "silkNLSFCB2ICDFNBMB", "silkNLSFCB2BITSNBMBQ5", "silkNLSFDeltaMinNBMBQ15")

	// --- NLSF WB codebook (tables_NLSF_CB_WB.c) ---
	emitSlice(&b, "silkNLSFCB1WBQ8", "silkNLSFCB1WBQ8 mirrors silk_NLSF_CB1_WB_Q8.", "byte", t["wbCB1NLSFQ8"], 16)
	emitSlice(&b, "silkNLSFCB1WBWghtQ9", "silkNLSFCB1WBWghtQ9 mirrors silk_NLSF_CB1_WB_Wght_Q9.", "int16", t["wbCB1WghtQ9"], 16)
	emitSlice(&b, "silkNLSFCB1ICDFWB", "silkNLSFCB1ICDFWB mirrors silk_NLSF_CB1_iCDF_WB.", "byte", t["wbCB1ICDF"], 12)
	emitSlice(&b, "silkNLSFPredWBQ8", "silkNLSFPredWBQ8 mirrors silk_NLSF_PRED_WB_Q8.", "byte", t["wbPredQ8"], 12)
	emitSlice(&b, "silkNLSFCB2SelectWB", "silkNLSFCB2SelectWB mirrors silk_NLSF_CB2_SELECT_WB.", "byte", t["wbEcSel"], 16)
	emitSlice(&b, "silkNLSFCB2ICDFWB", "silkNLSFCB2ICDFWB mirrors silk_NLSF_CB2_iCDF_WB.", "byte", t["wbEcICDF"], 9)
	emitSlice(&b, "silkNLSFCB2BITSWBQ5", "silkNLSFCB2BITSWBQ5 mirrors silk_NLSF_CB2_BITS_WB_Q5.", "byte", t["wbEcRatesQ5"], 9)
	emitSlice(&b, "silkNLSFDeltaMinWBQ15", "silkNLSFDeltaMinWBQ15 mirrors silk_NLSF_DELTA_MIN_WB_Q15.", "int16", t["wbDeltaMinQ15"], 12)
	emitNLSFCB(&b, "silkNLSFCBWB", "silkNLSFCBWB mirrors silk_NLSF_CB_WB (silk/tables_NLSF_CB_WB.c).", t["wbScalars"],
		"silkNLSFCB1WBQ8", "silkNLSFCB1WBWghtQ9", "silkNLSFCB1ICDFWB", "silkNLSFPredWBQ8",
		"silkNLSFCB2SelectWB", "silkNLSFCB2ICDFWB", "silkNLSFCB2BITSWBQ5", "silkNLSFDeltaMinWBQ15")

	return format.Source([]byte(b.String()))
}

// emitSlice writes a 1-D var declaration `var name = []elemType{ ... }`.
func emitSlice(b *strings.Builder, name, doc, elemType string, vals []int, perLine int) {
	fmt.Fprintf(b, "// %s\n", doc)
	fmt.Fprintf(b, "var %s = []%s{\n", name, elemType)
	writeRows(b, vals, perLine)
	fmt.Fprintf(b, "}\n\n")
}

// emitArray2D writes a fixed-size 2-D array var declaration
// `var name = [rows][cols]elemType{ {...}, ... }` from row-major vals.
func emitArray2D(b *strings.Builder, name, doc, elemType string, rows, cols int, vals []int) {
	fmt.Fprintf(b, "// %s\n", doc)
	fmt.Fprintf(b, "var %s = [%d][%d]%s{\n", name, rows, cols, elemType)
	for r := range rows {
		b.WriteString("\t{")
		for c := range cols {
			fmt.Fprintf(b, "%d,", vals[r*cols+c])
			if c != cols-1 {
				b.WriteString(" ")
			}
		}
		b.WriteString("},\n")
	}
	fmt.Fprintf(b, "}\n\n")
}

// emitPtrSlice writes a slice-of-slices var referencing already-emitted leaf
// vars, mirroring libopus's arrays of table pointers.
func emitPtrSlice(b *strings.Builder, name, doc, elemType string, subNames []string) {
	fmt.Fprintf(b, "// %s\n", doc)
	fmt.Fprintf(b, "var %s = [][]%s{%s}\n\n", name, elemType, strings.Join(subNames, ", "))
}

// emitNLSFCB writes a silkNLSFCBStruct literal. scalars = [nVectors, order,
// quantStepSize_Q16, invQuantStepSize_Q6]; the eight names are the leaf-table
// vars in struct-field order.
func emitNLSFCB(b *strings.Builder, name, doc string, scalars []int, cb1, wght, cb1icdf, pred, ecsel, ecicdf, ecrates, dmin string) {
	fmt.Fprintf(b, "// %s\n", doc)
	fmt.Fprintf(b, "var %s = silkNLSFCBStruct{\n", name)
	fmt.Fprintf(b, "\tnVectors:           %d,\n", scalars[0])
	fmt.Fprintf(b, "\torder:              %d,\n", scalars[1])
	fmt.Fprintf(b, "\tquantStepSizeQ16:   %d,\n", scalars[2])
	fmt.Fprintf(b, "\tinvQuantStepSizeQ6: %d,\n", scalars[3])
	fmt.Fprintf(b, "\tcb1NLSFQ8:          %s,\n", cb1)
	fmt.Fprintf(b, "\tcb1WghtQ9:          %s,\n", wght)
	fmt.Fprintf(b, "\tcb1ICDF:            %s,\n", cb1icdf)
	fmt.Fprintf(b, "\tpredQ8:             %s,\n", pred)
	fmt.Fprintf(b, "\tecSel:              %s,\n", ecsel)
	fmt.Fprintf(b, "\tecICDF:             %s,\n", ecicdf)
	fmt.Fprintf(b, "\tecRatesQ5:          %s,\n", ecrates)
	fmt.Fprintf(b, "\tdeltaMinQ15:        %s,\n", dmin)
	fmt.Fprintf(b, "}\n\n")
}
